import "../global/assets/css/globals.css";
import type { Metadata } from "next"; 

interface Props {
  children: React.ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, }: Readonly<Props>) {
  return (
    <html lang="es">
      <body>
        {children}
      </body>
    </html>
  );
}
